### ISSUE TITLE
what's up?

### ISSUE THREAD

**Issue by porres** [megrimm/pd-percolate#1]
So, what's up with this? Can I compile? Can we put up in deken?

**Comment by porres** [comment]
I'm about to include STK instruments to https://github.com/porres/pd-else

**Comment by megrimm** [comment]
yo...
this is forked from the svn repo. yeah it compiled 4 years ago when I tried but haven't touched since then so I do not remember much. give it a shot! 
...and yeah throw up in deken. let me know if you need help.
your on a roll!!!

**Comment by porres** [comment]
awesome

**Comment by porres** [comment]
I'll either steal it and put it in "else", or make a new library out of it called "ooze"

**Comment by porres** [comment]
but I can put it up in deken if I build it :)

**Comment by megrimm** [comment]
might want to keep "percolate" name hence someone getting upset? :) idk... yeah it would be better as individual *.pd_darwin files....

**Comment by megrimm** [comment]
also... all the help files need to be renamed to fit current convention. ill split the work with you if you tell me what to do. i like to either be taking orders or giving them.... one or the other :)

**Comment by porres** [comment]
well, I got really disappointed with this library, so really will think of another way around to implement STK instruments, either as another library or into the one I have

**Comment by megrimm** [comment]
disappointed with the sounds? or the compiling difficulties?

I do remember it being pretty cool like 10-15 years ago... :)

**Comment by porres** [comment]
with the sounds, but seems to be the objects themselves as well, buggy, badly designed, badly documented.

Well, I have to admit I've gone a little crazy recently, can't take it anymore these old libraries, so I decided to make my own crap. It's probably just me gone wild and out of my mind... I keep finding everything kinda inaceptable and/or disappointing...

**Comment by porres** [comment]
just saying...
